# This is a basic workflow that is manually triggered

name: Azure Resource Group teardown

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name of Resource Group to teardown'
        # Default value if no value is explicitly provided
        default: 'rg-MercuryHealth'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "teardown"
  teardown:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Runs a single command using the runners shell
    - name: Tear Down Azure RG
      run: echo "Hello ${{ inputs.name }}"

    - name: Ensure Resource Group is UnLocked
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          #az group lock delete --name DontDeleteMe --resource-group ${{ env.Azure_Resource_GroupName }}

    - name: Delete Resource Group
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          #az group delete --name ${{ env.Azure_Resource_GroupName }}
